# Generated by Django 3.2.3 on 2021-05-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210518_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='sharable_link',
            field=models.CharField(default='http://127.0.0.1/photo/dF8BGlo6oDuX', max_length=255, unique=True),
        ),
    ]
