# Generated by Django 3.2.3 on 2021-05-18 13:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_photo_sharable_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='img_url',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='sharable_link',
            field=models.CharField(default='http://127.0.0.1/photo/H6GvxYz1lpm5', max_length=255, unique=True),
        ),
    ]
